### ISSUE TITLE
[BUG] Game freezes when consuming liquids and food

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [bugthesda/Fallout76-Issue-Tracker#25]
Game occasionally will freeze (sounds can still be heard) after consuming liquids: Bourbon, RadAway, Wine, Vodka, Blood Pack, Dirty/Boiled/Purified Water, etc.

**Desktop:**
 - OS: Windows 8.1 Pro
 - GPU: GeForce GTX 1050 Ti
 - Game Version: v1.2.2.9

**To Reproduce**
1. Go to Inventory -> AID.
2. Click or use SPACEBAR on either of these: RadAway, Bourbon, Wine, Vodka, Dirty/Boiled Water, Ionized Meat.
3. There is a chance that game will freeze (For me, it happens very frequently).

**Expected behavior**
Drink liquid consumable or eat food without any problems.

**Screenshots**
Not applicable.

**Comment by akarnokd** [comment]
Same for me on 2 different desktops. Windows 7 & 10. Consuming food or buffing chems. Did not happen to Win 7 before patch 6.

**Comment by tesivo** [comment]
Same for me, drinking a lot of dirty water consecutively.

**Comment by 0xfeeddeadbeef** [comment]
I'm no longer observing this issue in Wastelanders update, closing for now.
