### ISSUE TITLE
[BUG] Fo76 Player Icons Resetting

### ISSUE THREAD

**Issue by ghost** [bugthesda/Fallout76-Issue-Tracker#27]
Describe the bug
The icons for the players are resetting to the default Vault Boy icon.

PS4 Post-Patch 7 Hotfix

To Reproduce
1. Load the game into a world
2. Go to the social side bar.
3. Notice the default player icon.

Expected behavior
The last displayed icon should stay assigned between sessions.

Additional context
Changing the icon prior to loading the world doesn't work either. This scenario will have the icon assigned but not displayed. To fix trying to change prior to loading, the icon will need to be unequipped and re-equipped.

**Comment by ghost** [comment]
To add, the social menu sometimes does show the properly equipped icon but in a party, the icon will be the default.

**Comment by RaidenXS** [comment]
It appears the icon resets in the party section of the HUD. Not sure it it affects controlled Workshops.

**Comment by ghost** [comment]
Fixed as of Patch 9
